source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
# 消除所有警告
inhibit_all_warnings!

install! 'cocoapods',
# 生成多个 Xcodeproj
:generate_multiple_pod_projects => true,
# 支持增量安装
:incremental_installation => true

target 'MEAdvSDK_Example' do
  pod 'MEAdvSDK', :path => '../'

  target 'MEAdvSDK_Tests' do
    inherit! :search_paths

    
  end
end
